_target_: data_wrappers.finetune_garment_token_data_wrapper.GarmentTokenDataWrapper
batch_size: 64
sequence_length: 260
panel_classification: ./assets/data_configs/panel_classes_condenced.json
filter_by_params: ./assets/data_configs/param_filter.json
token_dir: /home/w4756677/garment/garment_foundation_model/sewformer/SewFormer/assets/data/garment_token_for_finetuning_07232024.npy
stop_token: 50256
panel_start: 50513
panel_end: 50514