defaults:
  - optimizer: adamw
  - scheduler: warm_cosine
  - _self_
_target_: trainers.dresscode_trainer.DressCodeTrainer
_recursive_: false
lr: 0.0006
grad_accumulation_steps: 1
batch_size: 128
steps_per_epoch: 5000
max_norm: 1.0
epoches: 200
log_freq: 1
random_seed: 42
eval_freq: 1
scheduler:
  multiplier: 1
  eta_min: 6e-5
  warmup_steps: 715
optimizer: 
  weight_decay: 0.1
  eps: 1e-8
  betas: [0.9, 0.95]


