defaults:
  - optimizer: adamw
  - scheduler: warm_cosine
  - _self_

_target_: trainers.finetune_garment_token_trainer_v2.FinetuneGarmentTokenTrainerV2
_recursive_: false

max_steps: 19073
max_norm: 1.0
steps_per_eval: 250 
steps_per_save: 5000
grad_accum_steps: 8
lr: 6e-4
scheduler:
  multiplier: 2
  eta_min: 6e-5
  warmup_steps: 715
optimizer: 
  weight_decay: 0.1
  eps: 1e-8
  betas: [0.9, 0.95]

