_target_: trainers.pcd_trainer_hydra.TrainerPCD
_recursive_: false
defaults: 
  - optimizer: adamw 
  - scheduler: warm_cosine
  
devices: [0]
epochs: 40
dry_run: False
lr: 0.0002
lr_pcd_encoder: 0
with_visualization: true 
return_stitches: true