# Transformer
_target_: models.decoders.panel_transformer.PanelTransformer
num_encoder_layers: 6 
num_decoder_layers: 6
dim_feedforward: 2048
d_model: 256 
dropout: 0.1
nhead: 8 
normalize_before: True
return_intermediate_dec: True
src_dim: 64