_target_: models.gpt2_token_regression.GPTTokenRegression
block_size: 150
n_layer: 24
n_head: 8
n_embd: 512
edge_loss_weight: 0.1
bin_num: 256
verts_bounds: [-3, -3, 5, 5]
transf_bounds: [-3, -3, -3, -1, -1, -1, -1, 3, 3, 3, 1, 1, 1, 1]