_target_: models.pcd2garment.garment_pcd_hydra.GarmentPCD
defaults:
  - criteria: criteria

pcd_encoder: 
  _target_: models.pcd2garment.pcd_encoder.AlignedShapeLatentPerceiver
  num_latents: 256
  embed_dim: 64
  point_feats: 3   # normal
  num_freqs: 8
  include_pi: false
  heads: 12
  width: 768
  num_encoder_layers: 8
  num_decoder_layers: 16
  use_ln_post: true
  init_scale: 0.25
  qkv_bias: false
  use_checkpoint: true
  flash: false

panel_decoder:
  _target_: models.decoders.panel_transformer.PanelTransformer
  num_encoder_layers: 6 
  num_decoder_layers: 6
  dim_feedforward: 2048
  d_model: 256 
  dropout: 0.1
  nhead: 8 
  normalize_before: True
  return_intermediate_dec: True
  src_dim: 256

edge_decoder:
  _target_: models.decoders.edge_transformer.EdgeTransformer
  d_model: 256
  nhead: 8 
  num_layers: 6
  dim_feedforward: 256
  dropout: 0.1
  activation: relu 
  normalize_before: False
  return_intermediate: True


pre_trained_encoder: /home/w4756677/garment/sewformer/Sewformer/pretrained_weights/pretrained_pcd_encoder.pt
freeze_pcd_encoder: true
posterior_dim: ${.panel_decoder.src_dim}
num_edges: 14