_target_: data.datasets.simple_gcd_dataset.SimpleGarmentCodeData

root_dir: <>
caption_dir: <>
sampling_rate: [0.5, 0.3, 0.2]
panel_classification: assets/panel_classes_garmentcodedata.json
split_file: assets/garmentcodedatav2_datasplit.json
