_target_: data.datasets.full_vlg_dataset.FullDataset

root_dir: /scratch/m000051/garment_gang/data/garmentcodedatav2
caption_dir: /scratch/m000051/garment_gang/data/long-caption-processed
editing_dir: /projects/m000051/data/vlg/gcd_editing
split_file: assets/garmentcodedatav2_datasplit.json
synth_root_dir: /scratch/m000051/garment_gang/data/synth_images
panel_classification: assets/panel_classes_garmentcodedata.json
edit_prompts_file: assets/editing.json
extra_parquet_file: /scratch/m000051/garment_gang/data/extras.parquet
# sampling_rate: [0.2, 0.2, 0.1, 0.3, 0.15, 0.05]
# sampling_rate: [0.1, 0.1, 0.0, 0.35, 0.35, 0.1]
sampling_rate: [0.4, 0.2, 0.1, 0.0, 0.3, 0.0]
# sampling_rate: [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]
