_target_: models.pcd2garment.pcd_encoder.AlignedShapeLatentPerceiver
num_latents: 256
embed_dim: 64
point_feats: 3   # normal
num_freqs: 8
include_pi: false
heads: 12
width: 768
num_encoder_layers: 8
num_decoder_layers: 16
use_ln_post: true
init_scale: 0.25
qkv_bias: false
use_checkpoint: true
flash: false