# Training configuration for Pattern Shape prediction model 
# (part I of NeuralTailor)

# 0.5 * stitch cls loss (focal loss) + 0.005 * stitch ce loss + 5 * panel loss
defaults: 
  - data_wrapper: neural_tailor_data_wrapper
  - trainer: dresscode_trainer
  - system: my_system
  - experiment: gpt2_experiment
  - model: gpt2_garment_token
  - _self_

model:
  block_size: 150

experiment:
  run_name: train_neural_tailor


precision: bf16
eval_only: False
gen_only: False
eval_train: False
eval_val: True
pre_trained: null
model_type: regression
storage_dir: null
hydra:
  run:
    dir: /miele/george/garment/sewformer/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}