# Training configuration for Pattern Shape prediction model 
# (part I of NeuralTailor)

# 0.5 * stitch cls loss (focal loss) + 0.005 * stitch ce loss + 5 * panel loss
defaults: 
  - data_wrapper: garment_token_data_wrapper
  - model: gpt2
  - trainer: text_trainer
  - system: my_system
  - experiment: gpt2_experiment
  - _self_

model:
  ignore_index: null  # ignore padding token
  block_size: 256
  vocab_size: 143

experiment:
  run_name: garment_token_run

trainer:
  _target_: trainers.garment_token_trainer.GarmentTokenTrainer
  total_batch_size: 131072

test_only: False
random_seed: 42
pre_trained: null
storage_dir: null
from_pretrained: null