# Training configuration for Pattern Shape prediction model 
# (part I of NeuralTailor)

# 0.5 * stitch cls loss (focal loss) + 0.005 * stitch ce loss + 5 * panel loss
defaults: 
  - data_wrapper: text_data_wrapper
  - model: gpt2
  - trainer: text_trainer
  - system: my_system
  - experiment: gpt2_experiment

test_only: False
random_seed: 42
pre_trained: null
storage_dir: null
from_pretrained: null