# Training configuration for Pattern Shape prediction model 
# (part I of NeuralTailor)

# 0.5 * stitch cls loss (focal loss) + 0.005 * stitch ce loss + 5 * panel loss
defaults: 
  - dataset: gcd_dataset
  - garment_tokenizer: regression_garment_tokenizer
  - _self_

model:
  edge_loss_weight: 0.1
  num_freq: 9
  num_regression_layers: 2

optimizer: 
  lr: 0.0006
  beta1: .9
  beta2: 0.95

wandb_info:
  wandb_dir: /miele/george/garment/sewformer
  wandb_cache_dir: /miele/george/garment/sewformer/cache


project: aipparel
run_name: aipparel_llava_next_mistral_7b
run_id: null
run_local_path: null


version: llava-hf/llava-v1.6-mistral-7b-hf
precision: bf16
eval_only: False
gen_only: False

# training
from_start: False
resume: null

grad_accumulation_steps: 1
num_steps: 10000
save_freq: 500
warmup_steps: 100
batch_size: 4

hydra:
  run:
    dir: /miele/george/garment/sewformer/outputs/${project}/${run_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
