# Training configuration for Pattern Shape prediction model 
# (part I of NeuralTailor)

# 0.5 * stitch cls loss (focal loss) + 0.005 * stitch ce loss + 5 * panel loss
defaults: 
  - train_garment_neural_tailor_regression
  - override data_wrapper/dataset/garment_tokenizer: dresscode_garment_tokenizer_token
  - override model: gpt2_token
  - _self_


data_wrapper:
  collate_fn: data.data_wrappers.collate_fns.collate_fn_dresscode

experiment:
  run_name: train_neural_tailor_token

model:
  block_size: 282

precision: bf16
eval_only: False
gen_only: False
eval_train: False
eval_val: True
pre_trained: null
storage_dir: null
model_type: token
hydra:
  run:
    dir: /miele/george/garment/sewformer/outputs/dresscode/${now:%Y-%m-%d}/${now:%H-%M-%S}