# Training configuration for Pattern Shape prediction model 
# (part I of NeuralTailor)

# 0.5 * stitch cls loss (focal loss) + 0.005 * stitch ce loss + 5 * panel loss

experiment:
  project_name: pcd2garment
  run_name: exp4_data_fixed
  run_id: vcm6r0cd
  local_dir: /miele/george/garment/sewformer/wandb/run-20240703_192641-vcm6r0cd
  is_training: True

# ----- Dataset-related properties -----
dataset: 
  class: GarmentPCDDataset
  wrapper: RealisticDatasetPCDWrapper

  max_pattern_len: 23   # Overridden if panel_classification is specified
  max_panel_len: 14
  max_num_stitches: 28   # when training with stitches
  max_stitch_edges: 56

  element_size: 4
  rotation_size: 4
  translation_size: 3
  mesh_samples: 4096
  point_noise_w: 0.0
  include_posed_objects: true

  panel_classification: ./assets/data_configs/panel_classes_condenced.json 
  filter_by_params: ./assets/data_configs/param_filter.json
  

  standardize:
    gt_scale:
      outlines: [26.674109  , 29.560705,  1,  1]
      rotations: [1.3826834, 1.9238795, 1.2877939, 1.       ]
      stitch_tags: [119.964195, 109.62911, 105.657364]
      translations: [109.58753, 51.449017, 37.846794]
    gt_shift:
      outlines: [0., 0., 0, 0]
      rotations: [-0.38268343, -0.9238795, -1.,  0.]
      stitch_tags: [-59.99474 , -78.23346 , -52.926674]   
      translations: [-55.25636 , -20.001333, -17.086796]

data_split:
  type: percent
  split_on: folder
  valid_per_type: 5
  test_per_type: 5


# ----- Network Architecture --------

NN:
  pre-trained:  /miele/george/garment/sewformer/wandb/run-20240703_192641-vcm6r0cd/files/artifacts/vcm6r0cd/checkpoint_39.pth
  step-trained: 
  model: GarmentPCD

  # Transformer
  enc_layers: 6 
  dec_layers: 6
  dim_feedforward: 2048
  hidden_dim: 256 
  dropout: 0.1
  nheads: 8 
  num_queries: 25
  pre_norm: True

  # ----- Shape Encoder -----
  shape_encoder: 
    num_latents: 256
    embed_dim: 64
    point_feats: 3   # normal
    num_freqs: 8
    include_pi: false
    heads: 12
    width: 768
    num_encoder_layers: 8
    num_decoder_layers: 16
    use_ln_post: true
    init_scale: 0.25
    qkv_bias: false
    use_checkpoint: true
    flash: false

  pre-trained_pcd_encoder: /home/w4756677/garment/sewformer/Sewformer/pretrained_weights/pretrained_pcd_encoder.pt
  freeze_pre-trained_pcd_encoder: false
  # ----- Losses ----
  loss:
    loss_components:  [shape, loop, rotation, translation, kl]  #  stitch, free_class, segmentation
    quality_components:  [shape, discrete, rotation, translation, 2d_chamfer]  # stitch, free_class
    loss_weight_dict:
      loop_loss_weight: 1.
      edge_loss_weight: 1. 
      rotation_loss_weight: 1. 
      translation_loss_weight: 1.
    stitches: ce                  # ce, simple
    lepoch: 0
    eos_coef: 0.1
    aux_loss: false
    kl_weight: 0.005
    panel_origin_invariant_loss: False
    panel_order_inariant_loss: False  # False to use ordering as in the data_config
    epoch_with_order_matching: 0
    order_by: shape_translation   # placement, translation, stitches, shape_translation

# ------- Trainer -----
trainer: 
  dry_run: False
  random_seed: 1
  batch_size: 64
  devices: [0]
  without_matcher: true
  epochs: 40
  lr: 0.0002
  lr_pcd_encoder: 1e-5
  optimizer: AdamW
  weight_decay: 1e-4
  lr_scheduling: "warm_cosine"
  lr_drop: 200
  clip_max_norm: 0.1
  early_stopping:
    window: 0.0001
    patience: 50
  with_visualization: true  # Log visualizations of predicted sewing patterns
  return_stitches: true



