defaults:
  - garment_tokenizer: default_gcd_garment_tokenizer

_target_: data.datasets.dataset_garmentcodedata_retarget.GarmentCodeDatasetResize
garment_tokenizer: 
  sf_only: False
  include_template_name: False
  num_tags: 108

root_dir: /miele/timur/garmentcodedata
size_file: ./assets/data_configs/size_map.json
image_size: 1024
vision_tower: openai/clip-vit-large-patch14 
panel_classification: ./assets/data_configs/panel_classes_garmentcodedata.json
body_type: default_body
filtered_data_txt: ./assets/data_configs/garmentcodedata_filtered_09142024.txt
data_folders: [
  "garments_5000_0"
]
load_by_dataname: ./assets/data_configs/garmentcodedata_list_resizing.txt
