defaults:
  - standardize: sewfactory_stats
  - data_split: full_training

class: GarmentDetrDataset
wrapper: RealisticDatasetDetrWrapper

max_pattern_len: 23   # Overridden if panel_classification is specified
max_panel_len: 14
max_num_stitches: 28   # when training with stitches
max_stitch_edges: 56

element_size: 4
rotation_size: 4
translation_size: 3
use_sim: true
use_smpl_loss: true
img_size: 1024
augment: true

panel_classification: ./assets/data_configs/panel_classes_condenced.json 
filter_by_params: ./assets/data_configs/param_filter.json