defaults:
  - garment_tokenizer: default_garment_tokenizer

_target_: data.datasets.dataset_garment_as_token_qva.QVAGarmentTokenDataset

garment_tokenizer: 
  sf_only: true
  include_template_name: False

root_dir: /miele/george/sewfactory
image_size: 1024
vision_tower: openai/clip-vit-large-patch14 
panel_classification: ./assets/data_configs/panel_classes_condenced.json 
filter_params: ./assets/data_configs/param_filter.json
load_by_dataname: ./assets/data_configs/sewfactory_datapoints_names.pkl
